# pdf_export.py - PDF Export for Sido AI
from fpdf import FPDF
import os
from datetime import datetime
import re

class PDFExporter:
    def __init__(self):
        self.pdf = None
    
    def create_business_plan_pdf(self, business_name: str, content: str):
        """Create a PDF business plan"""
        try:
            pdf = FPDF()
            pdf.add_page()
            
            # Title
            pdf.set_font("Arial", "B", 20)
            pdf.set_text_color(0, 102, 0)  # Kenyan green
            pdf.cell(0, 15, f"Business Plan: {business_name}", ln=True, align="C")
            
            # Subtitle
            pdf.set_font("Arial", "I", 12)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 10, f"Generated by Sido AI - Kenya's Smartest Business Assistant", ln=True, align="C")
            pdf.cell(0, 10, f"Date: {datetime.now().strftime('%d/%m/%Y')}", ln=True, align="C")
            pdf.ln(10)
            
            # Separator
            pdf.set_draw_color(0, 102, 0)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(10)
            
            # Content
            pdf.set_font("Arial", "", 11)
            pdf.set_text_color(0, 0, 0)
            
            # Clean and format content
            clean_content = re.sub(r'\*\*([^*]+)\*\*', r'\1', content)
            lines = clean_content.split('\n')
            
            for line in lines:
                if line.strip():
                    # Check if line is a header (starts with numbers or special chars)
                    if re.match(r'^[\d.]+', line.strip()) or line.strip().startswith('•'):
                        pdf.set_font("Arial", "B", 11)
                        pdf.multi_cell(0, 8, line.strip())
                        pdf.set_font("Arial", "", 11)
                    elif ':' in line and len(line.split(':')) == 2:
                        # Bold the label
                        parts = line.split(':', 1)
                        pdf.set_font("Arial", "B", 11)
                        pdf.cell(0, 8, f"{parts[0]}:", ln=True)
                        pdf.set_font("Arial", "", 11)
                        if parts[1].strip():
                            pdf.multi_cell(0, 6, parts[1].strip())
                    else:
                        pdf.multi_cell(0, 6, line.strip())
                    pdf.ln(2)
            
            # Footer
            pdf.set_y(-30)
            pdf.set_draw_color(0, 102, 0)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(5)
            pdf.set_font("Arial", "I", 8)
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 10, f"Generated by Sido AI - {datetime.now().strftime('%Y')} | 🇰🇪 Kenya", align="C")
            
            # Save file
            filename = f"business_plan_{business_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            pdf.output(filename)
            return filename
        except Exception as e:
            return f"Error generating PDF: {str(e)}"
    
    def create_invoice_pdf(self, invoice_data: dict):
        """Create a PDF invoice"""
        try:
            pdf = FPDF()
            pdf.add_page()
            
            # Header
            pdf.set_font("Arial", "B", 24)
            pdf.set_text_color(0, 102, 0)
            pdf.cell(0, 15, "INVOICE", ln=True, align="C")
            pdf.ln(5)
            
            # Invoice details
            pdf.set_font("Arial", "B", 12)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(100, 8, f"Invoice #: {invoice_data.get('invoice_no', 'INV-001')}", ln=True)
            pdf.cell(100, 8, f"Date: {invoice_data.get('date', datetime.now().strftime('%d/%m/%Y'))}", ln=True)
            pdf.cell(100, 8, f"Due Date: {invoice_data.get('due_date', datetime.now().strftime('%d/%m/%Y'))}", ln=True)
            pdf.ln(5)
            
            # Separator
            pdf.set_draw_color(0, 102, 0)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(5)
            
            # Client info
            pdf.set_font("Arial", "B", 12)
            pdf.cell(0, 8, "Bill To:", ln=True)
            pdf.set_font("Arial", "", 12)
            pdf.cell(0, 8, invoice_data.get('client', 'Client Name'), ln=True)
            pdf.cell(0, 8, invoice_data.get('client_address', 'Client Address'), ln=True)
            pdf.ln(5)
            
            # Items table header
            pdf.set_font("Arial", "B", 11)
            pdf.set_fill_color(0, 102, 0)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(80, 10, "Description", border=1, fill=True)
            pdf.cell(30, 10, "Qty", border=1, fill=True, align="C")
            pdf.cell(40, 10, "Rate (KSh)", border=1, fill=True, align="R")
            pdf.cell(40, 10, "Total (KSh)", border=1, fill=True, align="R")
            pdf.ln()
            
            # Items
            pdf.set_font("Arial", "", 11)
            pdf.set_text_color(0, 0, 0)
            items = invoice_data.get('items', [{'desc': 'Service', 'qty': 1, 'rate': 10000}])
            total = 0
            
            for item in items:
                pdf.cell(80, 8, item.get('desc', 'Service'), border=1)
                pdf.cell(30, 8, str(item.get('qty', 1)), border=1, align="C")
                pdf.cell(40, 8, f"{item.get('rate', 10000):,.2f}", border=1, align="R")
                subtotal = item.get('qty', 1) * item.get('rate', 10000)
                total += subtotal
                pdf.cell(40, 8, f"{subtotal:,.2f}", border=1, align="R")
                pdf.ln()
            
            # Totals
            pdf.ln(5)
            pdf.set_font("Arial", "B", 12)
            pdf.cell(150, 10, "Subtotal:", align="R")
            pdf.cell(40, 10, f"{total:,.2f}", align="R")
            pdf.ln()
            
            vat = total * 0.16
            pdf.cell(150, 10, "VAT (16%):", align="R")
            pdf.cell(40, 10, f"{vat:,.2f}", align="R")
            pdf.ln()
            
            pdf.set_font("Arial", "B", 14)
            pdf.set_text_color(0, 102, 0)
            pdf.cell(150, 10, "Total:", align="R")
            pdf.cell(40, 10, f"{(total + vat):,.2f}", align="R")
            pdf.ln(10)
            
            # Payment details
            pdf.set_font("Arial", "B", 11)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(0, 8, "Payment Details:", ln=True)
            pdf.set_font("Arial", "", 11)
            pdf.cell(0, 8, "M-Pesa Paybill: 9305680", ln=True)
            pdf.cell(0, 8, "Account Number: SidoAI", ln=True)
            pdf.cell(0, 8, "Bank Transfer: [Your Bank Name]", ln=True)
            pdf.ln(5)
            
            # Footer
            pdf.set_y(-30)
            pdf.set_draw_color(0, 102, 0)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(5)
            pdf.set_font("Arial", "I", 8)
            pdf.set_text_color(150, 150, 150)
            pdf.cell(0, 10, f"Generated by Sido AI | 📧 Payments to: M-Pesa Paybill 9305680", align="C")
            
            # Save file
            filename = f"invoice_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
            pdf.output(filename)
            return filename
        except Exception as e:
            return f"Error generating PDF: {str(e)}"

# Initialize PDF exporter
pdf_exporter = PDFExporter()

def generate_pdf(content_type: str, content_data: dict):
    """Generate a PDF - main function to call from Sido AI"""
    if content_type == "business_plan":
        result = pdf_exporter.create_business_plan_pdf(
            content_data.get("name", "Business"),
            content_data.get("content", "")
        )
    elif content_type == "invoice":
        result = pdf_exporter.create_invoice_pdf(content_data)
    else:
        return "❌ Unknown PDF type. Supported: business_plan, invoice"
    
    if result and not result.startswith("Error"):
        return f"""
✅ **PDF Created Successfully!**

**File:** {result}
**Type:** {content_type.replace('_', ' ').title()}

📄 The PDF has been generated and saved.

💡 **Tip:** You can view or download the file from your server.
"""
    else:
        return f"❌ {result}"

# For testing
if __name__ == "__main__":
    print("📄 PDF Export for Sido AI")
    test_data = {
        "name": "Test Business",
        "content": "Test content for PDF generation."
    }
    result = generate_pdf("business_plan", test_data)
    print(result)